version: '3.9'

services:

  db:
    image: mariadb:lts
    restart: unless-stopped
    # logging:
    #   driver: none
    command: ["--max-allowed-packet=512M"]
    # ports:
    #   - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - default

  wordpress:
    image: wordpress:fpm-alpine
    depends_on:
      - db
    restart: unless-stopped
    # logging:
    #   driver: none
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_CONFIG_EXTRA:
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', '6379');
        define('WP_REDIS_MAXTTL', '900');
        define('WP_REDIS_PREFIX', 'wp-');
        define('WP_REDIS_KEY_SALT', 'salt');
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./www:/var/www/html
    networks:
      - default

  # wp:
  #   image: wordpress:cli
  #   depends_on:
  #     - wordpress
  #   entrypoint: ['wp', '--allow-root']
  #   env_file: .env
  #   environment:
  #     WORDPRESS_DB_HOST: db:3306
  #     WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
  #     WORDPRESS_DB_USER: '${MYSQL_USER}'
  #     WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
  #   volumes:
  #     - ./www:/var/www/html
  #   networks:
  #     - default

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - wordpress
    restart: unless-stopped
    # logging:
    #   driver: none
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    networks:
      - default

  redis:
    image: redis:alpine
    depends_on:
      - db
    # logging:
    #   driver: none
    restart: unless-stopped
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - default

  adminer:
    image: adminer:standalone
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - default

  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin:apache
  #   restart: unless-stopped
  #   ports:
  #     - 8008:80
  #   env_file: .env
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
  #     MEMORY_LIMIT: 2048
  #     UPLOAD_LIMIT: 2G
  #   networks:
  #     - default

volumes:
  db-data:
  redis-data:

networks:
  default:
    driver: bridge